stages:
    - test

run_tests:
    stage: test
    image: python:3.10
    before_script:
        - pip install --upgrade pip
        - pip install .
        - pip install pytest
    script:
     - cd "~/rdfdf/tests/test_corpus_table"
     - python -m pytest